[tool.mypy]
plugins = "pydantic.mypy"
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
install_types = true
non_interactive = true
show_column_numbers = true

[[tool.mypy.overrides]]
disallow_incomplete_defs = false
module = ["tests.*"]
