[tool.mypy]
plugins = "pydantic.mypy"
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
install_types = true
non_interactive = true
show_column_numbers = true

[[tool.mypy.overrides]]
disallow_incomplete_defs = false
module = ["tests.*"]

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format=true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]


[tool.ruff.lint]
# extend-select=['D']
# ignore = [
#     "D100",  # missing docstring in public module
#     "D104",  # missing docstring in public package
#     "D105",  # missing docstring in magic method
#     "D107",  # missing docstring in __init__
# ]

[tool.ruff.lint.pydocstyle]
convention="google"
